pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Define Docker configuration within the script block
                    docker.image('maven:3.9.0').inside {
                        sh 'mvn -B -DskipTests clean package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Run tests inside the same Docker container
                    docker.image('maven:3.9.0').inside {
                        sh 'mvn test'
                    }
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Run deliver script inside the same Docker container
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
